const columns = [
  { name: "NAME", uid: "name", sortable: true },
  { name: "AGE", uid: "age", sortable: true },
  { name: "EMAIL", uid: "email", sortable: true },
  { name: "CONTACT", uid: "contact" },
  { name: "DISEASE", uid: "disease", sortable: true },
  { name: "STATUS", uid: "status", sortable: true },
  { name: "ACTIONS", uid: "actions" },
];

const statusOptions = [
  { name: "Admitted", uid: "Admitted" },
  { name: "Discharged", uid: "Discharged" },
  { name: "UnderTreatment", uid: "UnderTreatment" },
];

const users = [
  {
    id: 1,
    name: "John Doe",
    age: 34,
    email: "john.doe@example.com",
    contact: "+1-555-1234",
    disease: { name: "Common Cold", severity: "non-serious" },
    status: "Admitted",
  },
  {
    id: 2,
    name: "Jane Smith",
    age: 29,
    email: "jane.smith@example.com",
    contact: "+1-555-5678",
    disease: { name: "Pneumonia", severity: "serious" },
    status: "Discharged",
  },
  {
    id: 3,
    name: "Michael Brown",
    age: 47,
    email: "michael.brown@example.com",
    contact: "+1-555-8765",
    disease: { name: "Diabetes", severity: "serious" },
    status: "UnderTreatment",
  },
  {
    id: 4,
    name: "Emily Davis",
    age: 55,
    email: "emily.davis@example.com",
    contact: "+1-555-4321",
    disease: { name: "Hypertension", severity: "non-serious" },
    status: "Admitted",
  },
  {
    id: 5,
    name: "Sarah Wilson",
    age: 42,
    email: "sarah.wilson@example.com",
    contact: "+1-555-9876",
    disease: { name: "COVID-19", severity: "serious" },
    status: "Discharged",
  },
  {
    id: 6,
    name: "David Johnson",
    age: 36,
    email: "david.johnson@example.com",
    contact: "+1-555-6543",
    disease: { name: "Asthma", severity: "non-serious" },
    status: "UnderTreatment",
  },
  {
    id: 7,
    name: "Laura Martinez",
    age: 63,
    email: "laura.martinez@example.com",
    contact: "+1-555-3210",
    disease: { name: "Heart Disease", severity: "serious" },
    status: "Admitted",
  },
  {
    id: 8,
    name: "Chris Taylor",
    age: 31,
    email: "chris.taylor@example.com",
    contact: "+1-555-6789",
    disease: { name: "Migraine", severity: "non-serious" },
    status: "UnderTreatment",
  },
  {
    id: 9,
    name: "Anna Anderson",
    age: 27,
    email: "anna.anderson@example.com",
    contact: "+1-555-5432",
    disease: { name: "Tuberculosis", severity: "serious" },
    status: "Discharged",
  },
  {
    id: 10,
    name: "James Clark",
    age: 50,
    email: "james.clark@example.com",
    contact: "+1-555-1098",
    disease: { name: "Common Cold", severity: "non-serious" },
    status: "Admitted",
  },
];

export { columns, statusOptions, users };
