import React from "react";
const columns = [
  { name: "ID", uid: "id", sortable: true },
  { name: "NAME", uid: "name", sortable: true },
  { name: "AGE", uid: "age", sortable: true },
  { name: "CATEGORY", uid: "category", sortable: true },
  { name: "TEAM", uid: "team" },
  { name: "EMAIL", uid: "email" },
  { name: "STATUS", uid: "status", sortable: true },
  { name: "ACTIONS", uid: "actions" },
];

const statusOptions = [
  { name: "Active", uid: "active" },
  { name: "Paused", uid: "paused" },
  { name: "Vacation", uid: "vacation" },
];

const users = [
  {
    id: 1,
    name: "Tony Reichert",
    category: "CEO",
    team: "Management",
    status: "active",
    age: "29",
    email: "tony.reichert@example.com",
  },
  {
    id: 2,
    name: "Zoey Lang",
    category: "Tech Lead",
    team: "Development",
    status: "paused",
    age: "25",
    email: "zoey.lang@example.com",
  },
  {
    id: 3,
    name: "Jane Fisher",
    category: "Sr. Dev",
    team: "Development",
    status: "active",
    age: "22",
    email: "jane.fisher@example.com",
  },
  {
    id: 4,
    name: "William Howard",
    category: "C.M.",
    team: "Marketing",
    status: "vacation",
    age: "28",
    email: "william.howard@example.com",
  },
  {
    id: 5,
    name: "Kristen Copper",
    category: "S. Manager",
    team: "Sales",
    status: "active",
    age: "24",
    email: "kristen.cooper@example.com",
  },
  {
    id: 6,
    name: "Brian Kim",
    category: "P. Manager",
    team: "Management",
    age: "29",
    email: "brian.kim@example.com",
    status: "active",
  },
  {
    id: 7,
    name: "Michael Hunt",
    category: "Designer",
    team: "Design",
    status: "paused",
    age: "27",
    email: "michael.hunt@example.com",
  },
  {
    id: 8,
    name: "Samantha Brooks",
    category: "HR Manager",
    team: "HR",
    status: "active",
    age: "31",
    email: "samantha.brooks@example.com",
  },
  {
    id: 9,
    name: "Frank Harrison",
    category: "F. Manager",
    team: "Finance",
    status: "vacation",
    age: "33",
    email: "frank.harrison@example.com",
  },
  {
    id: 10,
    name: "Emma Adams",
    category: "Ops Manager",
    team: "Operations",
    status: "active",
    age: "35",
    email: "emma.adams@example.com",
  },
  {
    id: 11,
    name: "Brandon Stevens",
    category: "Jr. Dev",
    team: "Development",
    status: "active",
    age: "22",
    email: "brandon.stevens@example.com",
  },
  {
    id: 12,
    name: "Megan Richards",
    category: "P. Manager",
    team: "Product",
    status: "paused",
    age: "28",
    email: "megan.richards@example.com",
  },
  {
    id: 13,
    name: "Oliver Scott",
    category: "S. Manager",
    team: "Security",
    status: "active",
    age: "37",
    email: "oliver.scott@example.com",
  },
  {
    id: 14,
    name: "Grace Allen",
    category: "M. Specialist",
    team: "Marketing",
    status: "active",
    age: "30",
    email: "grace.allen@example.com",
  },
  {
    id: 15,
    name: "Noah Carter",
    category: "IT Specialist",
    team: "I. Technology",
    status: "paused",
    age: "31",
    email: "noah.carter@example.com",
  },
  {
    id: 16,
    name: "Ava Perez",
    category: "Manager",
    team: "Sales",
    status: "active",
    age: "29",
    email: "ava.perez@example.com",
  },
  {
    id: 17,
    name: "Liam Johnson",
    category: "Data Analyst",
    team: "Analysis",
    status: "active",
    age: "28",

    email: "liam.johnson@example.com",
  },
  {
    id: 18,
    name: "Sophia Taylor",
    category: "QA Analyst",
    team: "Testing",
    status: "active",
    age: "27",
    email: "sophia.taylor@example.com",
  },
  {
    id: 19,
    name: "Lucas Harris",
    category: "Administrator",
    team: "Information Technology",
    status: "paused",
    age: "32",
    email: "lucas.harris@example.com",
  },
  {
    id: 20,
    name: "Mia Robinson",
    category: "Coordinator",
    team: "Operations",
    status: "active",
    age: "26",
    email: "mia.robinson@example.com",
  },
];

export { columns, users, statusOptions };
