const columns = [
  { name: "ITEM NAME", uid: "itemName", sortable: true },
  { name: "QUANTITY", uid: "quantity", sortable: true },
  { name: "CATEGORY", uid: "category", sortable: true },
  { name: "REASON FOR MAINTENANCE", uid: "maintenanceReason", sortable: false },
  { name: "DURATION", uid: "duration", sortable: false },
  { name: "STATUS", uid: "status", sortable: true },
  { name: "ACTIONS", uid: "actions" },
];

const statusOptions = [
  { name: "In Use", uid: "InUse" },
  { name: "Available", uid: "Available" },
  { name: "Under Maintenance", uid: "UnderMaintenance" },
];

const users = [
  {
    id: 1,
    itemName: "Motorcycles",
    quantity: 5,
    category: "Vehicle",
    maintenanceReason: "Engine failure",
    duration: "2 weeks",
    status: "Under Maintenance",
  },
  {
    id: 2,
    itemName: "Police Van",
    quantity: 2,
    category: "Vehicle",
    maintenanceReason: "Transmission issue",
    duration: "3 weeks",
    status: "Under Maintenance",
  },
  {
    id: 3,
    itemName: "Surveillance Drones",
    quantity: 10,
    category: "Equipment",
    maintenanceReason: "Battery replacement",
    duration: "1 week",
    status: "Under Maintenance",
  },
  {
    id: 4,
    itemName: "Body Armor",
    quantity: 15,
    category: "Equipment",
    maintenanceReason: "Stitching repairs",
    duration: "1 month",
    status: "Under Maintenance",
  },
  {
    id: 5,
    itemName: "Patrol Car",
    quantity: 4,
    category: "Vehicle",
    maintenanceReason: "Brake system check",
    duration: "2 weeks",
    status: "Under Maintenance",
  },
  {
    id: 6,
    itemName: "Radio Communication Devices",
    quantity: 20,
    category: "Equipment",
    maintenanceReason: "Software update",
    duration: "3 days",
    status: "Under Maintenance",
  },
  {
    id: 7,
    itemName: "K9 Unit Vehicles",
    quantity: 3,
    category: "Vehicle",
    maintenanceReason: "AC repair",
    duration: "1 week",
    status: "Under Maintenance",
  },
  {
    id: 8,
    itemName: "Tactical Helmets",
    quantity: 25,
    category: "Equipment",
    maintenanceReason: "Safety inspections",
    duration: "2 weeks",
    status: "Under Maintenance",
  },
  {
    id: 9,
    itemName: "Fire Extinguishers",
    quantity: 30,
    category: "Equipment",
    maintenanceReason: "Inspection and refill",
    duration: "1 week",
    status: "Under Maintenance",
  },
  {
    id: 10,
    itemName: "First Aid Kits",
    quantity: 12,
    category: "Equipment",
    maintenanceReason: "Restocking supplies",
    duration: "4 days",
    status: "Under Maintenance",
  },
];

export { columns, statusOptions, users };
