const columns = [
  { name: "ITEM NAME", uid: "itemName", sortable: true },
  { name: "ASSIGNED STATION", uid: "assignedStation", sortable: true },
  { name: "QUANTITY", uid: "quantity", sortable: true },
  { name: "CATEGORY", uid: "category", sortable: true },
  { name: "ACTIONS", uid: "actions" },
];

const statusOptions = [
  { name: "In Use", uid: "InUse" },
  { name: "Available", uid: "Available" },
  { name: "Under Maintenance", uid: "UnderMaintenance" },
];

const users = [
  {
    id: 1,
    itemName: "Handcuffs",
    assignedStation: "Bhopal Police Station",
    quantity: 50,
    category: "Equipment",
    status: "Available",
  },
  {
    id: 2,
    itemName: "Patrol Car",
    assignedStation: "Indore Police Station",
    quantity: 3,
    category: "Vehicle",
    status: "In Use",
  },
  {
    id: 3,
    itemName: "Bulletproof Vests",
    assignedStation: "Gwalior Police Station",
    quantity: 20,
    category: "Equipment",
    status: "Available",
  },
  {
    id: 4,
    itemName: "Tear Gas Canisters",
    assignedStation: "Jabalpur Police Station",
    quantity: 100,
    category: "Equipment",
    status: "Available",
  },
  {
    id: 5,
    itemName: "Motorcycles",
    assignedStation: "Ujjain Police Station",
    quantity: 5,
    category: "Vehicle",
    status: "Under Maintenance",
  },
  {
    id: 6,
    itemName: "Police Radios",
    assignedStation: "Sagar Police Station",
    quantity: 40,
    category: "Equipment",
    status: "In Use",
  },
  {
    id: 7,
    itemName: "Surveillance Cameras",
    assignedStation: "Bhopal Police Station",
    quantity: 15,
    category: "Equipment",
    status: "Available",
  },
  {
    id: 8,
    itemName: "K9 Unit Dogs",
    assignedStation: "Indore Police Station",
    quantity: 4,
    category: "Animals",
    status: "In Use",
  },
  {
    id: 9,
    itemName: "Traffic Cones",
    assignedStation: "Gwalior Police Station",
    quantity: 200,
    category: "Equipment",
    status: "Available",
  },
  {
    id: 10,
    itemName: "Fire Extinguishers",
    assignedStation: "Jabalpur Police Station",
    quantity: 30,
    category: "Safety Equipment",
    status: "Available",
  },
  {
    id: 11,
    itemName: "First Aid Kits",
    assignedStation: "Ujjain Police Station",
    quantity: 10,
    category: "Medical Supplies",
    status: "Available",
  },
  {
    id: 12,
    itemName: "Mobile Command Unit",
    assignedStation: "Sagar Police Station",
    quantity: 1,
    category: "Vehicle",
    status: "In Use",
  },
  {
    id: 13,
    itemName: "Gas Masks",
    assignedStation: "Bhopal Police Station",
    quantity: 25,
    category: "Safety Equipment",
    status: "Available",
  },
  {
    id: 14,
    itemName: "Body Cameras",
    assignedStation: "Indore Police Station",
    quantity: 30,
    category: "Equipment",
    status: "In Use",
  },
  {
    id: 15,
    itemName: "Patrol Boats",
    assignedStation: "Gwalior Police Station",
    quantity: 2,
    category: "Vessel",
    status: "Available",
  },
  {
    id: 16,
    itemName: "Drones",
    assignedStation: "Jabalpur Police Station",
    quantity: 5,
    category: "Equipment",
    status: "Under Maintenance",
  },
];

export { columns, statusOptions, users };
